CIRCUITPY_WIFI_SSID = ""
CIRCUITPY_WIFI_PASSWORD = ""
# Uncomment to enable Web Workflows on CircuitPython
#CIRCUITPY_WEB_API_PASSWORD = "changeme"
#CIRCUITPY_WEB_API_PORT = 8000

# SOUNDTHING CONFIG
SOUNDTHING_HOSTNAME = "soundthing.local"
#SOUNDTHING_PORT = 80
#SOUNDTHING_ARTIST_FONT = ""
#SOUNDTHING_ARTIST_FONT_SCALE = 1
#SOUNDTHING_TRACK_FONT = ""
#SOUNDTHING_TRACK_FONT_SCALE = 1
