CIRCUITPY_WIFI_SSID = ""
CIRCUITPY_WIFI_PASSWORD = ""

# SOUNDTHING CONFIG
SOUNDTHING_HOSTNAME = "soundthing.local"
#SOUNDTHING_ARTIST_FONT = ""
#SOUNDTHING_ARTIST_FONT_SCALE = 1
#SOUNDTHING_TRACK_FONT = ""
#SOUNDTHING_TRACK_FONT_SCALE = 1
